apiVersion: v1
kind: Service
metadata:
  name: service-quotes-api
  namespace: market-watcher
spec:
  selector:
    app: service-quotes-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000